server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
app:
  service:
    base_url: "https://api.brevo.com"
    send_path: "/v3/smtp/email"
    api-key: "${BREVO_API_KEY}"