version: "4"
name: booking-service
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/identity-service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      PROFILE_SERVICE_URL: http://profile-service:8081/profile/internal

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongodb:27017/post-service?authSource=admin

  profile-service:
    build:
      context: ./profile-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: secret123

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongodb:27017/notification-service?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BREVO_API_KEY: ${BREVO_API_KEY}

